project_id = "lrhefsrcvleluprpwhkj"

[functions.create-reservation]
verify_jwt = false

[functions.admin-action]
verify_jwt = true

[functions.generate-description]
verify_jwt = true

[functions.menu-chat]
verify_jwt = false